apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - cronjob.yaml

commonLabels:
  app: secret-rotation
  project: k8sbox

