apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/user/gitops-repo
    targetRevision: v1.0.0
    path: apps/my-app/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: false
    syncOptions:
      - CreateNamespace=true

