{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pdb-manager.serviceAccountName" . }}
  labels:
    {{- include "pdb-manager.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pdb-manager.fullname" . }}
  labels:
    {{- include "pdb-manager.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pdb-manager.fullname" . }}
  labels:
    {{- include "pdb-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pdb-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pdb-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

