apiVersion: v2
name: health-checks
description: A Helm chart for health-checks
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - health-checks
maintainers:
  - name: Your Name
    email: your.email@example.com

