apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpa-custom-metrics
  labels:
    app: hpa-custom-metrics
spec:
  selector:
    matchLabels:
      app: hpa-custom-metrics
  endpoints:
  - port: http
    path: /metrics/prometheus
    interval: 30s


