apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset-database.fullname" . }}
  labels:
    {{- include "statefulset-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "statefulset-database.selectorLabels" . | nindent 4 }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset-database.fullname" . }}-postgresql
  labels:
    {{- include "statefulset-database.labels" . | nindent 4 }}
    component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "statefulset-database.selectorLabels" . | nindent 4 }}
    component: postgresql
{{- end }}

