apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-pss.yaml
  - rbac.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - database-deployment.yaml
  - network-policy-frontend.yaml
  - network-policy-backend.yaml
  - network-policy-database.yaml

commonLabels:
  project: k8sbox
  security: zero-trust

