apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - example-application.yaml

commonLabels:
  app: custom-operator
  project: k8sbox

